stages:
  - build
  - test

build-latest:
  stage: build
  image: rust:latest
  script:
    - apt-get update
    - apt-get install -y libsdl2-dev libsdl2-ttf-dev
    - cargo build --verbose

test-latest:
  stage: test
  image: rust:latest
  script:
    - apt-get update
    - apt-get install -y libsdl2-dev libsdl2-ttf-dev
    - cargo test --verbose
  allow_failure: true
