[package]
name = "guion_sdl2"
version = "0.1.0"
authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guion = { path = "../guion" }
#qwutils = { git = "https://github.com/qwertz19281/rust_utils", rev = "473447e77a14d935b705088a134f1cc71633311e" }
qwutils = { path = "../qwutils" }

[dependencies.sdl2]
version = "0.33"
default-features = false
features = ["ttf"]