[package]
name = "guion_sdl2"
version = "0.1.0"
authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guion = { git = "https://git.mkg20001.io/ferionve/guion", rev = "488a44039f3e1819aea69309bb9da29aaf29a6ac" }
#guion = { path = "../guion" }
#TODO qwutils should export qwutils
qwutils = { git = "https://github.com/qwertz19281/rust_utils", rev = "3dd92de46947d65ec59a3c2aa8a885d09171ad4c" }
#qwutils = { path = "../qwutils" }

[dependencies.sdl2]
version = "0.33"
default-features = false
features = ["ttf"]