[package]
name = "guion_sdl2"
version = "0.1.1"

authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

description = "Backend for guion"
categories = ["gui"]
keywords = ["gui","ui","sdl2","sdl"]
license = "MIT OR Apache-2.0"

repository = "https://github.com/ferionve/guion_sdl2"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guion = { version = "0.2.0", git = "https://github.com/FerionVE/guion", rev = "f38395c44f130bca81aeea69792b6f27e68aef9b" }
#guion = { path = "../guion" }
#TODO qwutils should export qwutils
qwutils = { version = "0.1.1", git = "https://github.com/qwertz19281/rust_utils", rev = "c828ec4d864524e8846f25fc34f17e606accf3cc" }
#qwutils = { path = "../qwutils" }

[dependencies.sdl2]
version = "0.33"
default-features = false
features = ["ttf"]
#apt install libsdl2-dev libsdl2-ttf-dev

[profile.release]
lto = true
codegen-units = 1
