[package]
name = "guion_sdl2"
version = "0.1.0"
authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guion = { path = "../guion" }

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["ttf"]