[package]
name = "guion_sdl2"
version = "0.2.0-dev2"

authors = ["qwertz19281 <dellen903@gmail.com>"]
edition = "2018"

description = "Backend for guion"
categories = ["gui"]
keywords = ["gui","ui","sdl2","sdl"]
license = "MIT OR Apache-2.0"

repository = "https://github.com/ferionve/guion_sdl2"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guion = { version = "0.2.0-dev2", git = "https://github.com/FerionVE/guion", rev = "74bc6f711eb6158e47edfb105db80b8c02ae6586" }
#guion = { path = "../guion" }
#TODO qwutils should export qwutils
qwutils = { version = "0.1.1", git = "https://github.com/qwertz19281/rust_utils", rev = "c828ec4d864524e8846f25fc34f17e606accf3cc" }
#qwutils = { path = "../qwutils" }

[dependencies.sdl2]
version = "0.34"
default-features = false
features = []
#apt install libsdl2-dev libsdl2-ttf-dev

[dependencies.rusttype]
version = "0.9"
features = ["gpu_cache"]

[profile.release]
lto = true
codegen-units = 1
